// <auto-generated />

using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    internal class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Business.Desenvolvedor", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("varchar(200)");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(200)");

                b.HasKey("Id");

                b.ToTable("Desenvolvedores");
            });

            modelBuilder.Entity("Business.LancamentoDeHora", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("timestamp without time zone");

                b.Property<Guid?>("DesenvolvedorId")
                    .HasColumnType("uuid");

                b.Property<DateTime>("HoraFim")
                    .HasColumnType("TIMESTAMP");

                b.Property<DateTime>("HoraInicio")
                    .HasColumnType("TIMESTAMP");

                b.Property<Guid?>("ProjetoId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("DesenvolvedorId");

                b.HasIndex("ProjetoId");

                b.ToTable("Lancamentos");
            });

            modelBuilder.Entity("Business.Projeto", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("DataCadastro")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasColumnType("varchar(200)");

                b.HasKey("Id");

                b.ToTable("Projetos");
            });

            modelBuilder.Entity("Business.LancamentoDeHora", b =>
            {
                b.HasOne("Business.Desenvolvedor", "Desenvolvedor")
                    .WithMany()
                    .HasForeignKey("DesenvolvedorId");

                b.HasOne("Business.Projeto", "Projeto")
                    .WithMany()
                    .HasForeignKey("ProjetoId");
            });
#pragma warning restore 612, 618
        }
    }
}