version: "3"
services:
    web:
        build: .
        ports:
            - "1433:1433"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "admin123*"
            ACCEPT_EULA: "Y"
            DATABASE: "dbPonto"